### ISSUE TITLE
Installation: default /mnt/thinx folder is not DRY and neither created automatically

### ISSUE THREAD

**Issue by suculent** [suculent/thinx-device-api#100]
Installer scripts is missing. It should require:
1) data volume path
2) SSL domain or cert path
3) admin e-mail
4) contents for config.json

Optionally:
- Mailgun
- Slack
`GOOGLE_ANALYTICS_ID`
`ROLLBAR_ACCESS_TOKEN`
`CRISP_WEBSITE_ID`
`API_HOSTNAME`
`APP_HOSTNAME`
`LANDING_HOSTNAME`
`SQREEN...`
... etc.

Installer should do:
• Create /mnt structure with default data
• Generate initial logins for System MQTT, CouchDB and Redis, write  .env files with only required info...

FIrst run should do:
• Create databases, design docs and filters.
• Create initial user (acknowledged + gdpr) and log its generated admin password to console.
• Generate admin MQTT API key and enable using `mqtt_password`

**Comment by suculent** [comment]
Required installation steps are actually in test process `.circleci/config.yml`

**Comment by suculent** [comment]
Databases are now initialized programatically on first run.

**Comment by keyguru** [comment]
Everything is now solved using .env file for long time, closing.
