### ISSUE TITLE
eval can be harmful. (no-eval)

### ISSUE THREAD

**Issue by suculent** [suculent/thinx-device-api#130]
#### Message: `eval can be harmful. (no-eval)`

Should be implemented using Transformer, not the API core!
    
#### Occurred on:
+ **Commit**:  7c25215690a2fc6a3e065313e317b1695f5af4ee
+ **File**:    [lib/thinx/device.js](https://github.com/suculent/thinx-device-api/blob/7c25215690a2fc6a3e065313e317b1695f5af4ee/lib/thinx/device.js)
+ **LineNum**: [1347](https://github.com/suculent/thinx-device-api/blob/7c25215690a2fc6a3e065313e317b1695f5af4ee/lib/thinx/device.js#L1347)
+ **Code**:    `eval(unescape(code)); // should create the transformer(status, device); function`

    
#### Currently on:
+ **Commit**:  8fbe8fc8f71316eabc6442cd79587cbce10fcc49
+ **File**:    [lib/thinx/device.js](https://github.com/suculent/thinx-device-api/blob/8fbe8fc8f71316eabc6442cd79587cbce10fcc49/lib/thinx/device.js)
+ **LineNum**: [1303](https://github.com/suculent/thinx-device-api/blob/8fbe8fc8f71316eabc6442cd79587cbce10fcc49/lib/thinx/device.js#L1303)

**Comment by suculent** [comment]
This is just a fallback when transformer container is nit available. Should be removed for better security.

**Comment by keyguru** [comment]
This is valid in messenger, needs to be refactored to device's function that uses containerized call.

**Comment by suculent** [comment]
Solved in recent pull request.
