### ISSUE TITLE
Prefix file is not auto-created on installation

### ISSUE THREAD

**Issue by keyguru** [suculent/thinx-device-api#195]
Causes failing database creation in CouchDB. DBs are created without prefix and are not accessible.
User should hit the CouchDB Admin first before passing to this. Is it ever possible?

**Comment by suculent** [comment]
Can be worked-around manually by creating file `/mnt/data/conf/.thx_prefix' with some arbitrary secret inside it like "prefix".

**Comment by suculent** [comment]
A "preflight" or "installation" script that checks all important stuff before first run could be a solution.
