### ISSUE TITLE
`/devices` endpoint response form is not unified yet

### ISSUE THREAD

**Issue by qool** [suculent/thinx-device-api#369]
<img width="252" alt="image" src="https://user-images.githubusercontent.com/2158666/165931252-5b056459-28f5-4d7e-bd23-b8325d22fedd.png">

**Comment by suculent** [comment]
OK, but there's no `/devices` endpoint. There's either legacy `GET /api/user/devices` or `GET /api/v2/device`, which both return the same result.

```
callback(true, {
  success: true,
  response: devices
});
```
